Introduce immutable mode
continuationlabs/white-out pull request #17
Opened 2020-01-20 10:46 UTC by krystianolech

2020-01-20 21:01 UTC, arb requested changes
One small change request. This has been the simplest version of this feature request to date!

2020-01-21 08:42 UTC, krystianolech commented on test/index.js
> +        expect(source).to.be.equal(sourceDeepCopy);
good idea! I just fixed it

2020-01-27 14:04 UTC, arb commented
Sorry last request, can you delete the package.lock file? I didn't have one for this project and I'd like to add it myself in a future update.

2020-02-07 19:42 UTC, arb approved these changes

2020-02-07 19:43 UTC, merged